name: BTZs_ML
channels:
  - conda-forge
  - rdkit
  - defaults
dependencies:
  - ipykernel=5.3.4
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - jupyter_client=6.1.7
  - jupyter_core=4.7.1
  - jupyterlab=2.2.6
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=1.2.0
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - notebook=6.2.0
  - pickleshare=0.7.5
  - pip=21.0.1
  - python=3.6.12
  - python-dateutil=2.8.1
  - rdkit=2017.09.1
  - scipy=1.5.2
  - seaborn=0.11.1
  - pip:
    - ipywidgets==7.6.3
    - jupyterlab-widgets==1.0.0
    - numpy==1.19.5
    - pandas==1.1.2
    - scikit-learn==0.24.1
    - shap==0.36.0
    - xlrd==1.2.0
